### ISSUE TITLE
Second monitor doesn't open the right dashboard

### ISSUE THREAD

**Issue by FormelLMS** [RaceX58/RaceX.Dashboard.Manager#1]
Hi racex,
I really love the idea to automatically switch the dash. I have two screens for my dashboards. One Vocore and one normal 7 inch screen. 
On Vocore it seems to switch the dashboard correctly, but on the HDMI screen it doesn't work. My Simhub started with the latest dashboard and I've started a game, where it should have switched the dash, but it doesn't. Before I had saved this dashboard to the game in your plugin. 
As a second question: is it possible to delete an entry I've made?

**Comment by RaceX58** [comment]
Hey FormeILMS,

Do you mean you have set a default dashboard for the second monitor and it doesn't load when launching the corresponding game?
Could you please send a screen capture of the Dash Studios --> Settings page and also a capture of the RaceX Dashboard Manager --> Second monitor page ?

Concerning the possibility to delete an entry, I will add this function in the next release of the plugin.

RaceX

**Comment by FormelLMS** [comment]
Yes, thats right. On todays tries it even doesn't changed the Vocore Dash. And: It changes the default for TML The Bus to racing dash. Yesterday it was my bus dash. Somethins wrong here.
Now I can't change it anymore. Perhaps with uninstalling the Plugin somehow? Hoping you have an idea. Love to have this function :)
![1](https://user-images.githubusercontent.com/87239140/129092550-b4205cd1-2581-4868-80df-205f8c3fd534.JPG)
![2](https://user-images.githubusercontent.com/87239140/129092578-27c8cf00-b27c-403e-b889-30b3c14dcf34.JPG)

**Comment by RaceX58** [comment]
I've just released a new version of the plugin. It will give you the possibility to remove individuals or all entries.
Can you test removing all entries and see if the problem occurs again?

RaceX

**Comment by FormelLMS** [comment]
Hi RaceX,

tried the new Version now out, deleted all entries. Thats very fine. But unfortunately there is no change to the behaviour of my second screen. It doesn't switch the Dashboard :(

**Comment by RaceX58** [comment]
Closing as the second/third monitor option finally can't work with this plugin.
