### ISSUE TITLE
Defined cars dashboard scrollbar

### ISSUE THREAD

**Issue by pimo1983** [RaceX58/RaceX.Dashboard.Manager#2]
Hi RaceX,

Absolutely love this plugin! 
Was wondering if there is any way to add a scrollbar to the defined cars dashboard, as when the list becomes too long there is no way to delete cars at the bottom of the list?

**Comment by RaceX58** [comment]
Hello pimo1983,

Thank you for your feedback !

Could you please send me a screenshot of the plugin?

Thank you

**Comment by pimo1983** [comment]
![image](https://user-images.githubusercontent.com/93521143/139848713-c2175017-aa0c-403b-892c-92893bf76ab9.png)

Screenshot of the plugin defined cars dashboard. Hope this helps.

**Comment by RaceX58** [comment]
Thank you for the screenshot.
I will add the scrollbar in the next release of the plugin ;-)

RaceX

**Comment by pimo1983** [comment]
Fantastic, many thanks!

**Comment by RaceX58** [comment]
Resolved in #3
