### ISSUE TITLE
Set as default is not usable

### ISSUE THREAD

**Issue by thebaz** [RaceX58/RaceX.Dashboard.Manager#5]
I have a USBD480 on my GSI wheel... I can't use the "Set as default dashboard for the game" button (can't select)

**Comment by GRPDAN01** [comment]
I can't reproduce this issue. Could you please post a screen capture?

**Comment by RaceX58** [comment]
I can't reproduce this issue. Could you please add a screen capture?

**Comment by thebaz** [comment]
![Immagine 2022-03-18 155420](https://user-images.githubusercontent.com/7090323/159026391-5dc7b367-4d87-4512-9569-3dd196769bc6.png)

**Comment by RaceX58** [comment]
Resolved in #7

**Comment by thebaz** [comment]
Thanks, works as expected
